name: YAML montagem

on:
  push:
    branches: [ main ]

jobs:
  build-e-teste:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Começo do código (código-fonte)
        uses: actions/checkout@v3

      - name: 2. Construção do código (Montagem)
        run: echo "Construindo e ve se tudo está no lugar"

      - name: 3. Fazendo testes (Controle de Qualidade)
        run: echo "Teste rodandos e como funciona"

